# -*- coding: utf-8 -*-
"""Martingale Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvLvfYlyfcfnAUHxgupkBlOwwX5WSCv-
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import numpy as np
import matplotlib.pyplot as plt

apple = yf.Ticker("AAPL")
microsoft = yf.Ticker("MSFT")
google = yf.Ticker("GOOGL")
meta = yf.Ticker("META")
jpmorgan = yf.Ticker("JPM")
goldman = yf.Ticker("GS")
cola = yf.Ticker("KO")
walmart = yf.Ticker("WMT")
tesla = yf.Ticker("TSLA")
nvidia = yf.Ticker("NVDA")

hist = apple.history(period="1d")
print(hist.head())

hist = microsoft.history(period="1d")
print(hist.head())

hist = google.history(period="1d")
print(hist.head())

hist = meta.history(period="1d")
print(hist.head())

hist = jpmorgan.history(period="1d")
print(hist.head())

hist = goldman.history(period="1d")
print(hist.head())

hist = cola.history(period="1d")
print(hist.head())

hist = walmart.history(period="1d")
print(hist.head())

hist = tesla.history(period="1d")
print(hist.head())

hist = nvidia.history(period="1d")
print(hist.head())

start_date = '2021-1-29'
end_date = '2026-1-29'

data_apple = yf.download("AAPL", start=start_date, end=end_date)
print(data_apple.head())

data_miscrosoft = yf.download("MSFT", start=start_date, end=end_date)
print(data_miscrosoft.head())

data_google = yf.download("GOOGL", start=start_date, end=end_date)
print(data_google.head())

data_meta = yf.download("META", start=start_date, end=end_date)
print(data_meta.head())

data_jpmorgan = yf.download("JPM", start=start_date, end=end_date)
print(data_jpmorgan.head())

data_goldman = yf.download("GS", start=start_date, end=end_date)
print(data_goldman.head())

data_cola = yf.download("KO", start=start_date, end=end_date)
print(data_cola.head())

data_walmart = yf.download("WMT", start=start_date, end=end_date)
print(data_walmart.head())

data_tesla = yf.download("TSLA", start=start_date, end=end_date)
print(data_tesla.head())

data_nvidia = yf.download("NVDA", start=start_date, end=end_date)
print(data_nvidia.head())

stock_data = {
    "AAPL": data_apple,
    "MSFT": data_miscrosoft,
    "GOOGL": data_google,
    "META": data_meta,
    "JPM": data_jpmorgan,
    "GS": data_goldman,
    "KO": data_cola,
    "WMT": data_walmart,
    "TSLA": data_tesla,
    "NVDA": data_nvidia
}

def fixed_stop_loss(entry_price, direction, sl_pct=0.02):
    if direction == "LONG":
        return entry_price * (1 - sl_pct)
    else:
        return entry_price * (1 + sl_pct)

def trailing_stop_loss(direction, extreme_price, sl_pct=0.02):
    if direction == "LONG":
        return extreme_price * (1 - sl_pct)
    else:
        return extreme_price * (1 + sl_pct)

def simulation(multiplier, tp, sl, initial_capital, data, stop_type="fixed"):
    capital = initial_capital

    direction = "LONG"
    size = 1.0
    entry_price = None
    stop_price = None
    tp_price = None
    extreme_price = None

    trades = []
    equity_curve = []

    sl_count = 0
    tp_count = 0
    max_position_size = 1
    loss_streak = 0
    max_loss_streak = 0
    sl_sizes = []

    for date, row in data.iterrows():
        price = float(row["Close"])

        if entry_price is None:
            required_capital = size * price

            if required_capital > capital:
                size = 1.0
                direction = "SHORT" if direction == "LONG" else "LONG"
                loss_streak = 0
                entry_price = None
                stop_price = None
                tp_price = None
                extreme_price = None
                equity_curve.append({"date": date, "capital": capital})
                continue

            entry_price = price
            extreme_price = price

            if direction == "LONG":
                stop_price = entry_price * (1 - sl)
                tp_price = entry_price * (1 + tp)
            else:
                stop_price = entry_price * (1 + sl)
                tp_price = entry_price * (1 - tp)

            trades.append({
                "type": "ENTRY",
                "date": date,
                "price": price,
                "size": size,
                "direction": direction
            })

        if stop_type == "trailing":
            if direction == "LONG":
                extreme_price = max(extreme_price, price)
                stop_price = extreme_price * (1 - sl)
            else:
                extreme_price = min(extreme_price, price)
                stop_price = extreme_price * (1 + sl)

        exit_type = None

        if direction == "LONG":
            if price >= tp_price:
                exit_type = "TAKE_PROFIT"
            elif price <= stop_price:
                exit_type = "STOP"
        else:
            if price <= tp_price:
                exit_type = "TAKE_PROFIT"
            elif price >= stop_price:
                exit_type = "STOP"

        if exit_type:
            pnl = size * (price - entry_price)
            if direction == "SHORT":
                pnl *= -1

            capital += pnl

            trades.append({
                "type": exit_type,
                "date": date,
                "price": price,
                "size": size,
                "direction": direction,
                "pnl": pnl
            })

            equity_curve.append({"date": date, "capital": capital})

            if exit_type == "TAKE_PROFIT":
                tp_count += 1
                size = 1.0
                direction = "LONG"
                loss_streak = 0
            else:
                sl_count += 1
                sl_sizes.append(size)
                loss_streak += 1
                max_loss_streak = max(max_loss_streak, loss_streak)

                size *= multiplier
                direction = "SHORT" if direction == "LONG" else "LONG"

            max_position_size = max(max_position_size, size)

            entry_price = None
            stop_price = None
            tp_price = None
            extreme_price = None

        equity_curve.append({"date": date, "capital": capital})

    stats = {
        "sl_count": sl_count,
        "tp_count": tp_count,
        "max_position_size": max_position_size,
        "max_loss_streak": max_loss_streak,
        "sl_sizes": sl_sizes
    }

    return capital, stats, trades, equity_curve

def compute_drawdown(equity_curve):
    equity = pd.DataFrame(equity_curve)
    equity["peak"] = equity["capital"].cummax()
    equity["drawdown"] = (equity["capital"] - equity["peak"]) / equity["peak"]
    return equity["drawdown"].min()

def log_return(price_df):
    close_prices = price_df["Close"]
    if isinstance(close_prices, pd.DataFrame):
        close_prices = close_prices.iloc[:, 0]
    return np.log(close_prices / close_prices.shift(1)).dropna()

def drift(log_return):
  return log_return.mean()

def t_stat(log_return):
  mu = drift(log_return)
  sigma = log_return.std()
  n = len(log_return)
  return mu/(sigma/np.sqrt(n))

def martingale_classify(mu, t_stat, threshold = 2):
  if abs(t_stat) < threshold:
      return "Martingale"
  elif mu > 0:
      return "Submartingale"
  else:
      return "Supermartingale"

def autocorrelation(log_returns):
  return log_returns.autocorr(lag = 1)

def analyze_stock(price_df):
    log_returns = log_return(price_df)
    mu = float(drift(log_returns))
    t_stats = float(t_stat(log_returns))
    acf = float(autocorrelation(log_returns))
    classification = martingale_classify(mu, t_stats)

    return {
        "Drift (μ)": mu,
        "t-stat": t_stats,
        "Classification": classification,
        "Autocorr (lag-1)": acf
    }

def init_sl_tracking():
    return {
        "sl_count": 0,
        "sl_sizes": [],
        "sl_losses": [],
        "tp_count": 0,
        "max_position_size": 1,
        "current_loss_streak": 0,
        "max_loss_streak": 0
    }

def compute_win_rate(tracking):
    total = tracking["tp_count"] + tracking["sl_count"]
    if total == 0:
        return 0
    return tracking["tp_count"] / total

def plot_trades(data, trades, equity, ticker):
    fig, axs = plt.subplots(2, 1, figsize=(14, 10), sharex=True)

    axs[0].plot(data.index, data["Close"], label="Price", alpha=0.7)

    for t in trades:
        if t["type"] == "ENTRY":
            axs[0].scatter(
                t["date"], t["price"],
                marker="^" if t["direction"] == "LONG" else "v",
                color="blue"
            )
            axs[0].text(
                t["date"], t["price"],
                f'{t["size"]}',
                fontsize=8
            )

        elif t["type"] == "TAKE_PROFIT":
            axs[0].scatter(t["date"], t["price"], color="green", marker="o")

        elif t["type"] == "STOP":
            axs[0].scatter(t["date"], t["price"], color="red", marker="x")

    axs[0].set_title(f"{ticker} Price & Trades")
    axs[0].legend()

    equity_df = pd.DataFrame(equity)
    axs[1].plot(equity_df["date"], equity_df["capital"])
    axs[1].set_title("Equity Curve")
    axs[1].axhline(10000, linestyle="--", alpha=0.5)

    plt.show()

tp = .05
sl = .02
size = 1
capital = 10000
direction = "LONG"
entry_price = None
multiplier = 2

for ticker, data in stock_data.items():
    print(f"\n===== {ticker} =====")

    cap_fixed, stats_fixed, trades_fixed, equity_fixed = simulation(multiplier, tp, sl, capital, data, "fixed")

    cap_trailing, stats_trailing, trades_trailing, equity_trailing = simulation(multiplier, tp, sl, capital, data, "trailing")

    if ticker in ["AAPL", "MSFT", "GOOGL"]:
        plot_trades(data, trades_fixed, equity_fixed, f"{ticker} (Fixed SL)")
        plot_trades(data, trades_trailing, equity_trailing, f"{ticker} (Trailing SL)")

    print("Fixed Stop Loss:")
    print(f"  Final Capital: ${cap_fixed:.2f}")
    print(f"  Win Rate: {compute_win_rate(stats_fixed):.2%}")
    print(f"  Stop Loss Hits: {stats_fixed['sl_count']}")
    print(f"  Max Position Size: {stats_fixed['max_position_size']}")
    print(f"  Max Losing Streak: {stats_fixed['max_loss_streak']}")

    print("Trailing Stop Loss:")
    print(f"  Final Capital: ${cap_trailing:.2f}")
    print(f"  Win Rate: {compute_win_rate(stats_trailing):.2%}")
    print(f"  Stop Loss Hits: {stats_trailing['sl_count']}")
    print(f"  Max Position Size: {stats_trailing['max_position_size']}")
    print(f"  Max Losing Streak: {stats_trailing['max_loss_streak']}")
    print(analyze_stock(data))
    print("Fixed SL sizes:", stats_fixed["sl_sizes"])
    print("Trailing SL sizes:", stats_trailing["sl_sizes"])
    print("\n")

results = []

for m in [1.3, 1.5, 2.0, 2.5, 3.0]:
    cap, stats, trades, equity = simulation(
        multiplier=m,
        tp=tp,
        sl=sl,
        initial_capital=10000,
        data=data_apple,
        stop_type="fixed"
    )

    results.append({
        "Multiplier": m,
        "Final Capital": cap,
        "Max Position Size": stats["max_position_size"],
        "Stop Losses": stats["sl_count"],
        "Max Drawdown": compute_drawdown(equity)
    })

results_df = pd.DataFrame(results)
print(results_df)

results_df.set_index("Multiplier")[["Final Capital", "Max Drawdown"]].plot(
    kind="bar",
    figsize=(10,5),
    title="Multiplier Risk vs Reward Comparison"
)

plt.show()